# Ubuntu alapú image használata
FROM ubuntu:latest

# Környezeti változók beállítása a non-interaktív telepítéshez
ENV DEBIAN_FRONTEND=noninteractive

# Rendszer frissítése, Ansible, Python és SSH kliens telepítése
RUN apt-get update && \
    apt-get install -y ansible openssh-client python3 python3-pip iputils-ping nano less && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Az SSH host key checking letiltása a kényelmesebb tanulás érdekében
# (Ez NEM ajánlott éles környezetben!)
RUN mkdir -p /etc/ansible && \
	echo "Host *" > /etc/ansible/hosts_config && \
    echo "  StrictHostKeyChecking no" >> /etc/ansible/hosts_config && \
    echo "  UserKnownHostsFile /dev/null" >> /etc/ansible/hosts_config

# Ansible konfigurációs fájl beállítása, hogy használja az új host configot
ENV ANSIBLE_SSH_ARGS="-F /etc/ansible/hosts_config"

COPY controller/ansible.cfg /etc/ansible/ansible.cfg

COPY controller/hosts /etc/ansible/hosts

#ansadmin user létrehozása
RUN useradd -m -s /bin/bash ansadmin && \
    echo "ansadmin ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

#SSH kulcsok másolása az ansadmin felhasználóhoz
RUN mkdir -p /home/ansadmin/.ssh
COPY ans_key.pub /home/ansadmin/.ssh/authorized_keys
COPY ans_key /home/ansadmin/.ssh/id_rsa 
RUN chmod 700 /home/ansadmin/.ssh && \
    chmod 600 /home/ansadmin/.ssh/authorized_keys && \
    chmod 600 /home/ansadmin/.ssh/id_rsa && \
    chown -R ansadmin:ansadmin /home/ansadmin/.ssh

# Belépési pont beállítása, hogy a konténer fusson a háttérben
CMD ["tail", "-f", "/dev/null"]
